import Head from "next/head"
import Footer from "../components/Footer/Footer"
import Navbar from "../components/Navbar/Navbar"
import CTASection from "../components/CTASection"
import FoodSection from "../components/Menu/FoodSection"

export default function Menu() {
  return (
    <div>
      <Head>
        <title>Saint Tropez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="sans-serif">
        <Navbar active={true} />
        <FoodSection />
        <CTASection />
        <Footer />
      </main>
    </div>
  )
}
