import Head from "next/head"
import Image from "next/image"
import Details from "../components/Details/Details"
import Hero from "../components/Hero/Hero"
import Navbar from "../components/Navbar/Navbar"
import Spotify from "../components/Spotify"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Saint Tropez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="sans-serif">
        <Navbar />
        <Hero />
        <Details />
        <Spotify />
      </main>
    </div>
  )
}
