import Head from "next/head"
import CTASection from "../components/CTASection"
import Details from "../components/Details/Details"
import Footer from "../components/Footer/Footer"
import Hero from "../components/Hero/Hero"
import Navbar from "../components/Navbar/Navbar"
import Spotify from "../components/Spotify"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Saint Tropez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="sans-serif">
        <Navbar active={true} />
        {/* Navbar is fine */}
        <Hero />
        {/* Hero is fine */}
        <Details />
        {/* This is good. Map is a bit ugly but I think we can fix that. */}
        <Spotify />
        {/* Playlist not loading ?  */}
        <CTASection />
        <Footer />
        {/* Need to fill ig link also make target="_blank" */}
      </main>
    </div>
  )
}
